# It is gql file for server_manager


type User{
    userId: String!
    userName: String!
    password: String!
    createdProjects: [Project!]
    allowedProjects: [Project!]
}

type Project{
    projectId: String!
    projectName: String!
    createdBy: String
    allowedUsers: [String!]
    content: String
    language: String!
}

input userRegisterInput{
    userId: String!
    userName: String!
    password: String!
}
input userLoginInput{
    userId: String!
    password: String!
}

input userInputForAllowAccess{
    userId: String!
    projectId: String!
}
input CreateProjectInput{
    projectId: String!
    projectName: String!
    createdBy: String!
    allowedUsers: [String!]!
    content: String
    language: String!
}
input addProjectInput{
    userId: String!
    project: CreateProjectInput!
}
# input CreateCodeInput{
#     codeId: String!
#     projectId: String!
#     version: String!
#     date: String!
#     content: String!
# }
# input addNewVersionInput{
#     projectId: String!
#     code: CreateCodeInput!
# }
input queryUserInput{
    userId: String!
}
input queryProjectInput{
    projectId: String!
}
type Mutation{
    login(input: userLoginInput!): Boolean!
    register(input: userRegisterInput!): User!
    add_allowed_user(input: userInputForAllowAccess!): Project!
    create_project(input: addProjectInput!): User!
}

type Query{
    users: [User!]
    user(input: queryUserInput!): User!
    project(input: queryProjectInput!): Project!     
}

# 






